name: ESP-IDF Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: espressif/idf:release-v5.5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Build with idf.py
        run: |
          . $IDF_PATH/export.sh
          idf.py build

      - name: Report binary size
        run: |
          . $IDF_PATH/export.sh
          idf.py size
